Repository trianglefraternitymtu/trianglefraternitymtu.github.io, pull requests merged in 2018-09, with the labels that each got.

#53 Updated for 2018 date and registration form
  _events/pi-mile.md
Labels: markdown content

#54 Updating the map on the contact page.
  contact.md
Labels: enhancement, markdown content

#55 Timeline cleanup
  _includes/timeline.html
  _sass/_timeline.scss
Labels: enhancement, site styling
